[server]
headless = true
port = 8501
enableCORS = true
enableXsrfProtection = false
allowRunOnSave = true

[server.frameOptions]
sameOrigin = false

[browser]
gatherUsageStats = false

[theme]
primaryColor = "#4F00ED"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F5F5F5"
textColor = "#000000"
